version: 1
accounts:
  - name: Alice
    address: ''
    coins:
      - 1000000000000000utest
  - name: Bob
    address: ''
    coins:
      - 20000000000000000utest
  - name: validator
    address: ''
    coins:
      - 20000000000000000utest
client:
  openapi:
    path: docs/static/openapi.yml
validators:
  - name: validator
    bonded: 20000000000000000utest
genesis:
  chain_id: test-12
  app_state:
    staking:
      params:
        bond_denom: utest
